Add Google Cloud support
databricks/mlops-stacks pull request #40
Opened 2023-01-18 02:43 UTC by michael-chi

In related to  #39 

* GitHub Actions as the CI/CD platform.
* Ability to generate ML project from the cookiecutter template. Which allows the user to configure:
   - ML Project
   - CI/CD platform (Github Actions)
   - Choose Google Cloud as the cloud provider
   - Enable Feature Store
   - Production / Staging workspaces
   - ML experiment parent directory
   - Github branches
* Integration between GitHub Actions and Google Cloud.
   - Authentication through Workload Identity Pool.
   - Setup and configure required Google Cloud permissions / roles through Terraform.
* Add required configuration and setup instructions to the readme.

2023-08-01 14:02 UTC, stawo requested changes
Just few notes I managed to catch. Did not have time to completely review.

2023-08-01 14:02 UTC, stawo commented on {{cookiecutter.project_name}}/.mlops-setup-scripts/cicd/provider.tf
> +  // provision the S3 bucket referenced below and store appropriate credentials for accessing the bucket from CI/CD.
Fix comment to properly address Google Cloud Storage

2023-10-25 09:38 UTC, arpitjasa-db commented
Hi @michael-chi @stawo, we've made some pretty significant changes to MLOps Stacks since this PR was opened, would you be interested in updating your PR?

2023-10-25 13:35 UTC, stawo commented
@arpitjasa-db , I don't own this PR, I just did a small and incomplete review of it 😄 
Let's see if @michael-chi will update the PR following the latest changes.

2024-03-01 23:04 UTC, arpitjasa-db commented
Closing this since we now support GCP with https://github.com/databricks/mlops-stacks/pull/153

2024-03-01 23:04 UTC, closed without merging